set(LLVM_VERSION "20.1.2") 
set(LLVM_INSTALL_DIR "${CMAKE_SOURCE_DIR}/llvm")
set(LLVM_ARCHIVE_EXT ".tar.xz")
	
if(NOT CMAKE_HOST_SYSTEM_PROCESSOR)
	if(WIN32)
		if(DEFINED ENV{PROCESSOR_ARCHITECTURE})
			set(CMAKE_HOST_SYSTEM_PROCESSOR "$ENV{PROCESSOR_ARCHITECTURE}")
		elseif(DEFINED ENV{PROCESSOR_ARCHITEW6432})
			set(CMAKE_HOST_SYSTEM_PROCESSOR "$ENV{PROCESSOR_ARCHITEW6432}")
		endif()
	elseif(UNIX OR APPLE)
		execute_process(COMMAND uname -m OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_PROCESSOR OUTPUT_STRIP_TRAILING_WHITESPACE)
		if("${CMAKE_HOST_SYSTEM_PROCESSOR}" STREQUAL "i386")
			set(CMAKE_HOST_SYSTEM_PROCESSOR "x86")
		elseif("${CMAKE_HOST_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
			set(CMAKE_HOST_SYSTEM_PROCESSOR "amd64")
		endif()
	endif()
endif()

if (WIN32)
    if (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64|i[3-6]86|x86")
        set(LLVM_TARGET_NAME "clang+llvm-${LLVM_VERSION}-x86_64-pc-windows-msvc")
    elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "arm|arm64|aarch64")
        set(LLVM_TARGET_NAME "clang+llvm-${LLVM_VERSION}-aarch64-pc-windows-msvc")
    endif()
elseif(APPLE)
    if (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64|i[3-6]86|x86")
        set(LLVM_TARGET_NAME "LLVM-${LLVM_VERSION}-macOS-X64")
    elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "arm|arm64|aarch64")
        set(LLVM_TARGET_NAME "LLVM-${LLVM_VERSION}-macOS-ARM64")
    endif()
else()
    if (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|amd64|i[3-6]86|x86")
        set(LLVM_TARGET_NAME "LLVM-${LLVM_VERSION}-Linux-X64")
    elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "arm|arm64|aarch64")
        set(LLVM_TARGET_NAME "LLVM-${LLVM_VERSION}-Linux-ARM64")
    endif()
endif()

set(LLVM_ARCHIVE "${LLVM_TARGET_NAME}${LLVM_ARCHIVE_EXT}")
set(LLVM_DOWNLOAD_URL "https://github.com/llvm/llvm-project/releases/download/llvmorg-${LLVM_VERSION}/${LLVM_ARCHIVE}")
set(LLVM_ARCHIVE_PATH "${CMAKE_BINARY_DIR}/${LLVM_ARCHIVE}")

if (WIN32)
    set(BINARY_EXTENSION ".exe")
else()
    set(BINARY_EXTENSION "")
endif()

set(CLANG_BIN "${LLVM_INSTALL_DIR}/${LLVM_TARGET_NAME}/bin/clang${BINARY_EXTENSION}")
set(CLANGXX_BIN "${LLVM_INSTALL_DIR}/${LLVM_TARGET_NAME}/bin/clang++${BINARY_EXTENSION}")

if (NOT EXISTS ${CLANG_BIN})
    message(STATUS "[install_llvm] LLVM not found; downloading from ${LLVM_DOWNLOAD_URL}")
    
    file(DOWNLOAD
        "${LLVM_DOWNLOAD_URL}"
        "${LLVM_ARCHIVE_PATH}"
        SHOW_PROGRESS
        STATUS DOWNLOAD_STATUS
        LOG DOWNLOAD_LOG
    )

    file(MAKE_DIRECTORY "${LLVM_INSTALL_DIR}")

    execute_process(COMMAND tar -xf "${LLVM_ARCHIVE_PATH}" -C "${LLVM_INSTALL_DIR}"
        RESULT_VARIABLE TAR_RESULT
        OUTPUT_VARIABLE TAR_OUTPUT
        ERROR_VARIABLE TAR_ERROR
    )
endif()
