set(LLVM_HINT_DIRS
  ${LLVM_INSTALL_DIR}/${LLVM_TARGET_NAME}
  ${LLVM_INSTALL_DIR}
)

find_package(LLVM ${LLVM_VERSION} CONFIG REQUIRED HINTS ${LLVM_HINT_DIRS})

message(STATUS "[llvm_environment] LLVM_INCLUDE_DIRS     : ${LLVM_INCLUDE_DIRS}")
message(STATUS "[llvm_environment] LLVM_TOOLS_BINARY_DIR : ${LLVM_TOOLS_BINARY_DIR}")
message(STATUS "[llvm_environment] LLVM_LIBRARY_DIR      : ${LLVM_LIBRARY_DIR}")
